#基本属性 url、users、password
spring: 
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.127.0.0.1:3306/51-jianmo?characterEncoding=utf8
    userName: root
    password: root
#配置初始化大小、最小、最大
    initialSize: 5
    minIdle: 5
    maxActive: 50
#配置获取连接等待超时的时间
    maxWait: 60000
#配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
#配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
#打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
#配置监控统计拦截的filters
    filters: stat
#通常来说，只需要修改initialSize、minIdle、maxActive
